name: "Semantic release"

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ github.repository == 'molinfo-vienna/skin-doctor' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency: release
      
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.NERDD_APP_ID }}
        private-key: ${{ secrets.NERDD_APP_SECRET }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.11.0
      with:
        github_token: ${{ steps.app-token.outputs.token }}
